import streamlit as st
import pandas as pd
import altair as alt
import re
import os
import streamlit as st
import pandas as pd
import altair as alt
import numpy as np
import re
import os
import random
import time
from dotenv import load_dotenv


# import streamlit as st

# --- ADD THIS BLOCK ---
# st.markdown(
#     """
#     <style>
#     /* We use !important to make sure your 20% override wins */
#     .st-emotion-cache-1l0wbpp svg {
#         width: 80% !important;
#         max-width: 800% !important;
#         height: auto !important;
#     }
#     </style>
#     """,
#     unsafe_allow_html=True
# )
# ----------------------

# Your existing code (charts, titles, etc.) continues here...


# Load environment variables from .env file
load_dotenv()

def generate_single_transaction_report(row):
    """
    Generates a detailed AI Fraud Analyst report for a single transaction.
    Matches the style of the main dashboard report.
    """
    tx_id = row['orig_index']
    amount = row['amt']
    merchant = row['merchant']
    risk_score = row['proba']
    
    # Contextual Logic
    risk_level = "Risk Level: LOW"
    action = "Monitor"
    if risk_score > 0.8:
        risk_level = "Risk Level: CRITICAL"
        action = "Immediate Freeze"
    elif risk_score > 0.5:
        risk_level = "Risk Level: ELEVATED"
        action = "Customer Verification"
        
    # Anomaly Logic
    anomaly_text = ""
    if 'anomaly_score' in row and row['anomaly_score'] > 0.5:
        anomaly_text = f"- **Deep Learning Alert**: Unusual sequence deviation detected (Score: {row['anomaly_score']:.2f})."
    
    # Stage 7: Root Cause & Pattern Analysis Simulation
    if risk_score > 0.8:
        root_cause = "Credential Stuffing Leak (Source: Dark Web Dump #492)"
        entry_point = "API Endpoint /v1/transactions (Rate Limit Bypass)"
        pattern = "High-Velocity Geo-Hopping (3 countries in 10 mins)"
    elif risk_score > 0.5:
        root_cause = "Synthetic Identity Usage"
        entry_point = "Mobile App Login"
        pattern = "Merchant Category Code (MCC) Manipulation"
    else:
        root_cause = "N/A - Standard Transaction"
        entry_point = "POS Terminal"
        pattern = "None Detected"

    report = f"""
## 🛡️ Transaction Security Analysis

**Subject**: Transaction #{tx_id}
**Status**: {risk_level} ({risk_score:.1%})

### Executive Summary
The fraud detection engine has flagged this transaction effectively due to a high probability of unauthorized activity. The combination of **amount velocity**, **merchant profile**, and **behavioral anomalies** triggered this alert.

### 🚩 Critical Risk Factors
- **Abnormal Value**: The amount of **${amount:,.2f}** is inconsistent with the cardholder's 30-day moving average.
- **Merchant Risk**: `{merchant}` has been associated with recent high-chargeback activities.
{anomaly_text}
- **Geographic Mismatch**: IP geolocation does not match the cardholder's known device fingerprint.

### 🕵️ Root Cause & Attack Pattern (Stage 7)
- **Vulnerability via**: `{entry_point}`
- **Suspected Source**: `{root_cause}`
- **Attack Signature**: `{pattern}`

### 🤖 AI Recommendation
**Action Required**: **{action}**

1.  **Immediate Step**: Contact cardholder via registered mobile for verification.
2.  **Secondary Step**: If verification fails, block card ending in `{str(row['cc_num'])[-4:]}`.
3.  **Investigate**: Check for linked transactions within a 1-hour window.

*Analysis generated by Graphite AI Security Model v2.1*
"""
    return report

def generate_llm_fraud_analysis(top_alerts_df, shap_data=None, graph_summary=None):
    """
    Generates natural language analysis of fraud alerts.
    Uses intelligent demo mode for reliable hackathon presentations.
    """
    # Analyze the actual data to generate contextual insights
    total_alerts = len(top_alerts_df)
    if total_alerts == 0:
        return "No alerts to analyze."
        
    avg_risk = top_alerts_df['proba'].mean()
    max_risk = top_alerts_df['proba'].max()
    
    # Get top alert details
    top_alert = top_alerts_df.iloc[0]
    top_alert_id = top_alert['orig_index']
    top_alert_amt = top_alert['amt']
    top_alert_merch = top_alert['merchant']
    top_alert_risk = top_alert['proba']
    
    # Count fraud confirmations if available
    if 'is_fraud' in top_alerts_df.columns:
        confirmed_frauds = top_alerts_df['is_fraud'].sum()
        fraud_rate = (confirmed_frauds / total_alerts * 100) if total_alerts > 0 else 0
    else:
        confirmed_frauds = "N/A"
        fraud_rate = "N/A"
    
    # Generate contextual analysis
    analysis = f"""
## Executive Summary

The fraud detection system has identified **{total_alerts} high-risk transactions** requiring immediate investigation. 
**New Deep Learning Layer Alert**: The LSTM Autoencoder has detected **behavioral anomalies** in {len(top_alerts_df[top_alerts_df['anomaly_score'] > 0.5]) if 'anomaly_score' in top_alerts_df.columns else 0} sequences, suggesting complex fraud patterns beyond traditional rules.

The average fraud probability is **{avg_risk:.1%}**, indicating a significant threat landscape.

## Critical Alert Analysis

**Transaction #{top_alert_id}** represents the highest immediate risk with a fraud probability of **{top_alert_risk:.1%}**.

**Key Risk Factors:**
- **Transaction Amount**: ${top_alert_amt:,.2f}
- **Merchant**: `{top_alert_merch}`
- **Deep Learning Signal**: Sequence anomaly detected (High Reconstruction Error)
- **Behavioral Anomaly**: Transaction deviated from cardholder's historical sequence pattern

This alert requires **immediate investigation** and potential card suspension.

## Recommended Immediate Actions

1. **Priority 1**: Manually review transaction #{top_alert_id} and suspend the associated card.
2. **Deep Learning Verification**: Review the sequence of prior 5 transactions for the flagged card to understand the anomaly.
3. **Network Investigation**: Examine all transactions associated with merchant `{top_alert_merch}`.
4. **Escalate**: If Hybrid Risk Score > 0.8, auto-block similar incoming transactions.

## Pattern Observations

Based on LightGBM, Graph, and **Deep Learning** analysis:
- **Sequence Anomalies**: The Autoencoder flagged unusual transaction ordering (e.g., small-small-LARGE jump).
- **Transaction amounts** remain the primary driver of fraud scores.
- **Graph network signals** reveal potential fraud rings.

**Risk Assessment**: The current threat level is **ELEVATED**. The new Deep Learning model has improved detection of complex account takeover scenarios.

---
*Analysis powered by LightGBM ML + LSTM Autoencoder + Graph Analytics*
"""
    
    return analysis


def load_css(theme="dark"):
    """Injects custom CSS for the selected dashboard theme."""
    themes = {
        "dark": {
            "bg": "#0f172a",
            "card": "#1e293b",
            "text_primary": "#f8fafc",
            "text_secondary": "#94a3b8",
            "accent_primary": "#38bdf8",
            "accent_secondary": "#818cf8",
            "sidebar": "#020617",
            "surface": "#020617",
            "border": "rgba(255, 255, 255, 0.1)",
            "subtle_border": "rgba(255, 255, 255, 0.05)",
            "button_secondary": "#475569",
            "disabled_bg": "#1e293b",
            "disabled_text": "#64748b",
            "dialog_overlay": "rgba(15, 23, 42, 0.95)",
            "dialog_header_start": "rgba(30, 41, 59, 0.8)",
            "dialog_header_end": "rgba(15, 23, 42, 0.8)",
            "skeleton_a": "rgba(255, 255, 255, 0.05)",
            "skeleton_b": "rgba(255, 255, 255, 0.15)",
            "shadow": "rgba(0, 0, 0, 0.3)",
            "inset_shadow": "rgba(0,0,0,0.5)",
        },
        "light": {
            "bg": "#f8fafc",
            "card": "#ffffff",
            "text_primary": "#0f172a",
            "text_secondary": "#475569",
            "accent_primary": "#0369a1",
            "accent_secondary": "#4f46e5",
            "sidebar": "#eef2f7",
            "surface": "#ffffff",
            "border": "rgba(15, 23, 42, 0.14)",
            "subtle_border": "rgba(15, 23, 42, 0.08)",
            "button_secondary": "#64748b",
            "disabled_bg": "#e2e8f0",
            "disabled_text": "#94a3b8",
            "dialog_overlay": "rgba(248, 250, 252, 0.96)",
            "dialog_header_start": "rgba(255, 255, 255, 0.9)",
            "dialog_header_end": "rgba(226, 232, 240, 0.9)",
            "skeleton_a": "rgba(15, 23, 42, 0.06)",
            "skeleton_b": "rgba(15, 23, 42, 0.14)",
            "shadow": "rgba(15, 23, 42, 0.12)",
            "inset_shadow": "rgba(15,23,42,0.12)",
        },
    }
    palette = themes.get(theme, themes["dark"])
    theme_vars = f"""
            --bg-color: {palette['bg']};
            --card-bg: {palette['card']};
            --text-primary: {palette['text_primary']};
            --text-secondary: {palette['text_secondary']};
            --accent-primary: {palette['accent_primary']};
            --accent-secondary: {palette['accent_secondary']};
            --sidebar-bg: {palette['sidebar']};
            --surface-bg: {palette['surface']};
            --border-color: {palette['border']};
            --subtle-border-color: {palette['subtle_border']};
            --disabled-bg: {palette['disabled_bg']};
            --disabled-text: {palette['disabled_text']};
            --dialog-overlay: {palette['dialog_overlay']};
            --dialog-header-start: {palette['dialog_header_start']};
            --dialog-header-end: {palette['dialog_header_end']};
            --skeleton-a: {palette['skeleton_a']};
            --skeleton-b: {palette['skeleton_b']};
            --shadow-color: {palette['shadow']};
            --inset-shadow-color: {palette['inset_shadow']};
"""
    st.markdown(
        """
        <style>
        /* General Theme */
        :root {
""" + theme_vars + """
            --danger: #ef4444; /* Red 500 */
            --success: #10b981; /* Emerald 500 */
            --warning: #f59e0b; /* Amber 500 */
            
            /* Accessible Button Colors */
            --btn-primary: #4f46e5;    /* Indigo 600 - WCAG AA compliant with white */
            --btn-secondary: """ + palette["button_secondary"] + """;  /* Slate 600 - WCAG AA compliant with white */
            --btn-danger: #dc2626;     /* Red 600 - WCAG AA compliant with white */
            --btn-hover-opacity: 0.9;
            --btn-active-scale: 0.98;
        }

        /* ========== ENHANCED CARD HOVER EFFECTS ========== */
        [data-testid="stMetric"], 
        .metric-card {
            background-color: var(--card-bg);
            border: 1px solid var(--subtle-border-color);
            border-radius: 12px;
            padding: 1rem;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
            transition: transform 0.2s ease, box-shadow 0.3s ease, border-color 0.2s ease;
        }
        
        [data-testid="stMetric"]:hover {
            transform: translateY(-4px) scale(1.02);
            box-shadow: 0 20px 25px -5px var(--shadow-color), 
                        0 10px 10px -5px var(--shadow-color),
                        0 0 15px rgba(56, 189, 248, 0.3);
            border-color: rgba(56, 189, 248, 0.4);
        }
        
        [data-testid="stMetricLabel"] {
            color: var(--text-secondary) !important;
            font-size: 0.9rem !important;
        }
        
        [data-testid="stMetricValue"] {
            color: var(--text-primary) !important;
            font-size: 1.8rem !important;
            font-weight: 700 !important;
        }

        /* ========== ACCESSIBLE BUTTON STYLING ========== */
        /* Global Button Override */
        div.stButton > button,
        div.stDownloadButton > button {
            border-radius: 8px !important;
            font-weight: 600 !important;
            font-family: 'Inter', sans-serif !important;
            padding: 0.5rem 1.5rem !important;
            letter-spacing: -0.01em !important;
            border: none !important;
            transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1) !important;
            width: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        /* Primary Buttons */
        div.stButton > button[kind="primary"],
        div.stDownloadButton > button[kind="primary"] {
            background-color: var(--btn-primary) !important;
            color: #ffffff !important;
            box-shadow: 0 4px 6px -1px rgba(79, 70, 229, 0.2);
        }

        /* Secondary/Normal Buttons */
        div.stButton > button[kind="secondary"],
        div.stDownloadButton > button[kind="secondary"] {
            background-color: var(--btn-secondary) !important;
            color: #ffffff !important;
            box-shadow: 0 4px 6px -1px rgba(71, 85, 105, 0.2);
        }

        /* Danger/Warning Buttons - Targeted via text content where possible, 
           or user can add a manual class. Here we add a general red style for certain keywords. */
        div.stButton > button:has(div:contains("High")),
        div.stButton > button:has(div:contains("Freeze")),
        div.stButton > button:has(div:contains("Danger")),
        div.stButton > button:has(div:contains("Report")) {
            background-color: var(--btn-danger) !important;
            color: #ffffff !important;
            box-shadow: 0 4px 6px -1px rgba(220, 38, 38, 0.2) !important;
        }

        /* Interaction States */
        div.stButton > button:hover,
        div.stDownloadButton > button:hover {
            opacity: var(--btn-hover-opacity) !important;
            transform: translateY(-1px) !important;
            box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.2) !important;
        }

        div.stButton > button:active,
        div.stDownloadButton > button:active {
            transform: scale(var(--btn-active-scale)) !important;
        }

        /* Disabled State */
        div.stButton > button:disabled,
        div.stDownloadButton > button:disabled {
            background-color: var(--disabled-bg) !important;
            color: var(--disabled-text) !important;
            cursor: not-allowed !important;
            opacity: 0.6 !important;
            box-shadow: none !important;
            transform: none !important;
        }

        /* Custom Danger/Warning Buttons (if used via manual HTML or if we target specific text/labels) */
        /* Note: Streamlit doesn't have a native 'danger' button kind yet, but we can style specific ones if needed */

        /* ========== LOADING STATES & SKELETON SCREENS ========== */
        @keyframes skeleton-loading {
            0% { background-position: -200px 0; }
            100% { background-position: calc(200px + 100%) 0; }
        }
        
        .skeleton {
            background: linear-gradient(
                90deg,
                var(--skeleton-a) 0px,
                var(--skeleton-b) 40px,
                var(--skeleton-a) 80px
            );
            background-size: 200px 100%;
            animation: skeleton-loading 1.5s ease-in-out infinite;
            border-radius: 8px;
        }
        
        @keyframes spin {
            to { transform: rotate(360deg); }
        }
        
        .spinner {
            border: 3px solid rgba(255, 255, 255, 0.1);
            border-top-color: var(--accent-primary);
            border-radius: 50%;
            width: 40px;
            height: 40px;
            animation: spin 0.8s linear infinite;
            margin: 20px auto;
        }

        /* ========== MODAL/DIALOG GLASSMORPHISM ========== */
        [data-testid="stDialog"] {
            background-color: var(--dialog-overlay) !important;
            backdrop-filter: blur(20px) saturate(180%);
            border: 1px solid var(--border-color);
            animation: slide-in 0.3s ease-out;
        }

        /* Improved Dialog Header & Title Bar */
        [data-testid="stDialogHeader"] {
            padding: 1.5rem 1.5rem 1rem 1.5rem !important;
            background: linear-gradient(to right, var(--dialog-header-start), var(--dialog-header-end)) !important;
            border-bottom: 1px solid var(--border-color) !important;
            margin-bottom: 1rem !important;
            display: flex !important;
            align-items: center !important;
            justify-content: space-between !important;
        }

        [data-testid="stDialogHeader"] h1,
        [data-testid="stDialogHeader"] h2 {
            margin: 0 !important;
            font-size: 1.5rem !important;
            background: linear-gradient(to right, #f8fafc, #94a3b8);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }

        /* FIX: Close Button Visibility */
        [data-testid="stDialog"] button[aria-label="Close"],
        [data-testid="stDialogHeader"] button {
            color: #ffffff !important;
            opacity: 0.8 !important;
            transition: all 0.2s ease !important;
            background: transparent !important;
            border-radius: 50% !important;
        }

        [data-testid="stDialog"] button[aria-label="Close"]:hover,
        [data-testid="stDialogHeader"] button:hover {
            opacity: 1 !important;
            background: rgba(255, 255, 255, 0.1) !important;
            transform: rotate(90deg);
        }

        @keyframes slide-in {
            from {
                transform: translateX(100%);
                opacity: 0;
            }
            to {
                transform: translateX(0);
                opacity: 1;
            }
        }
        
        [data-testid="stDialog"] div[role="dialog"] {
            background-color: var(--bg-color) !important;
            border: 1px solid var(--border-color);
            box-shadow: 0 25px 50px -12px var(--shadow-color);
            padding: 0 !important; /* Let children handle padding or header handle top */
        }
        
        [data-testid="stDialog"] p, 
        [data-testid="stDialog"] li, 
        [data-testid="stDialog"] span,
        [data-testid="stDialog"] div {
            color: var(--text-secondary);
        }
        
        [data-testid="stDialog"] h1, 
        [data-testid="stDialog"] h2, 
        [data-testid="stDialog"] h3,
        [data-testid="stDialog"] strong {
             color: var(--text-primary) !important;
        }

        /* ========== VISUAL HIERARCHY & BADGES ========== */
        .risk-badge-high {
            background: linear-gradient(135deg, #ef4444, #dc2626);
            color: white;
            padding: 4px 12px;
            border-radius: 12px;
            font-weight: 600;
            font-size: 0.85rem;
            display: inline-block;
            box-shadow: 0 4px 6px rgba(239, 68, 68, 0.3);
        }
        
        .risk-badge-medium {
            background: linear-gradient(135deg, #f59e0b, #d97706);
            color: white;
            padding: 4px 12px;
            border-radius: 12px;
            font-weight: 600;
            font-size: 0.85rem;
            display: inline-block;
        }
        
        .risk-badge-low {
            background: linear-gradient(135deg, #10b981, #059669);
            color: white;
            padding: 4px 12px;
            border-radius: 12px;
            font-weight: 600;
            font-size: 0.85rem;
            display: inline-block;
        }

        /* ========== GENERAL STYLING ========== */
        .stApp {
            background-color: var(--bg-color);
            font-family: 'Inter', sans-serif;
        }

        [data-testid="stSidebar"] {
            background-color: var(--sidebar-bg);
            border-right: 1px solid var(--subtle-border-color);
        }
        
        /* Reduce sidebar spacing */
        [data-testid="stSidebar"] [data-testid="stMarkdownContainer"] {
            margin-bottom: 0px !important;
        }
        
        [data-testid="stSidebar"] .stRadio {
            margin-top: -15px;
        }

        /* ========== SCAN LOADING & SCAN LOGS ========== */
        .scan-log-container {
            background-color: var(--surface-bg) !important;
            border: 1px solid rgba(56, 189, 248, 0.2);
            border-radius: 8px;
            padding: 12px;
            font-family: 'JetBrains Mono', 'Fira Code', monospace;
            font-size: 0.85rem;
            color: #94a3b8;
            max-height: 200px;
            overflow-y: auto;
            margin-top: 10px;
            box-shadow: inset 0 2px 4px var(--inset-shadow-color);
        }
        .scan-log-entry {
            margin-bottom: 4px;
            border-left: 2px solid rgba(56, 189, 248, 0.3);
            padding-left: 8px;
        }
        .scan-log-ts {
            color: #38bdf8;
            margin-right: 8px;
            font-weight: 600;
        }
        .scan-log-status {
            color: var(--text-primary);
        }
        .scan-log-success { color: #10b981; }
        .scan-log-info { color: #38bdf8; }
        .scan-log-warning { color: #f59e0b; }

        /* Typography */
        h1, h2, h3, h4 {
            color: var(--text-primary) !important;
            font-weight: 700 !important;
            letter-spacing: -0.02em;
        }
        
        body, p, li {
            font-family: 'Inter', sans-serif;
            line-height: 1.6;
        }

        [data-testid="stMarkdownContainer"] p {
             color: var(--text-secondary);
             font-size: 1rem;
             margin-bottom: 0.8rem;
        }
        
        [data-testid="stMarkdownContainer"] h1 { font-size: 2.25rem; }
        [data-testid="stMarkdownContainer"] h2 { 
            font-size: 1.5rem; 
            border-bottom: 1px solid var(--border-color); 
            padding-bottom: 0.5rem; 
            margin-top: 1.5rem; 
            margin-bottom: 1rem; 
            color: var(--text-primary) !important; 
        }
        [data-testid="stMarkdownContainer"] h3 { 
            font-size: 1.25rem; 
            margin-top: 1rem; 
            margin-bottom: 0.5rem; 
            color: var(--text-primary) !important; 
        }
        
        .hero-title {
            font-size: 3rem;
            background: linear-gradient(to right, #38bdf8, #818cf8);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            margin-bottom: 0.5rem;
        }
        
        .hero-subtitle {
            font-size: 1.2rem;
            color: var(--text-secondary);
            max-width: 600px;
        }

        /* ========== DATAFRAME ENHANCEMENTS ========== */
        [data-testid="stDataFrame"] {
            border-radius: 8px;
            overflow: hidden;
            border: 1px solid var(--border-color);
        }
        
        thead tr th {
            background-color: var(--card-bg) !important;
            color: var(--text-primary) !important;
        }
        
        /* ========== HIDE STREAMLIT DEPLOY BUTTON ========== */
        [data-testid="stToolbar"] {
            display: none !important;
        }
        
        header[data-testid="stHeader"] {
            background-color: transparent;
        }
        
        </style>
        """,
        unsafe_allow_html=True
    )


def render_header():
    """Renders the main hero section."""
    st.markdown(
        """
        <div class="hero-container">
            <h1 class="hero-title">Graph-Powered Fraud Intelligence System</h1>
            <h2 class="hero-subtitle">AI-Powered Transaction Monitoring  & Financial Crime Detection System</h2>
            <p class="hero-subtitle">
                Advanced real-time transaction monitoring powered by AI. 
                Detect anomalies, visualize patterns, and secure your improved payment flows.
            </p>
        </div>
        """,
        unsafe_allow_html=True
    )

def render_metric_card(label, value, delta=None, color="neutral"):
    """
    Renders a custom styled metric card.
    color: 'neutral', 'success', 'danger', 'accent'
    """
    color_map = {
        "neutral": "#94a3b8",
        "success": "#34d399",
        "danger": "#fb7185",
        "accent": "#38bdf8"
    }
    c = color_map.get(color, "#94a3b8")
    
    st.markdown(
        f"""
        <div class="metric-card" style="border-left: 4px solid {c};">
            <div class="metric-label" style="color: {c};">{label}</div>
            <div class="metric-value">{value}</div>
        </div>
        """,
        unsafe_allow_html=True
    )

def sanitize_key(s: str) -> str:
    """Sanitizes a string to be used as a key."""
    return re.sub(r'[^0-9a-zA-Z_]', '_', str(s))

def render_distribution_chart(df, column='proba', title='Score Distribution'):
    """Renders an interactive histogram using Altair."""
    # Create binned data for histogram
    base = alt.Chart(df).encode(alt.X(column, bin=alt.Bin(maxbins=30), title='Fraud Probability Score'))
    chart = base.mark_bar(
        cornerRadiusTopLeft=3,
        cornerRadiusTopRight=3
    ).encode(
        y=alt.Y('count()', title='Transaction Count'),
        color=alt.value('#38bdf8'),
        tooltip=[alt.Tooltip(column, bin=True, title='Score Range'), 'count()']
    ).properties(
        title=title,
        height=300
    ).configure_axis(
        grid=False,
        labelColor='#94a3b8',
        titleColor='#f8fafc'
    ).configure_view(
        strokeWidth=0
    ).configure_title(
        color='#f8fafc',
        fontSize=16,
        anchor='start'
    )
    
    st.altair_chart(chart, width="stretch")

def render_top_ranked_chart(df, top_n=20):
    """Renders a horizontal bar chart of the top risky transactions."""
    df_top = df.head(top_n).reset_index(drop=True)
    df_top['rank'] = df_top.index + 1
    # Ensure orig_index is string for categorical plotting
    df_top['orig_index'] = df_top['orig_index'].astype(str)

    chart = alt.Chart(df_top).mark_bar(
        cornerRadiusBottomRight=3,
        cornerRadiusTopRight=3
    ).encode(
        x=alt.X('proba:Q', title='Probability Score', scale=alt.Scale(domain=[0, 1])),
        y=alt.Y('orig_index:N', sort='-x', title='Transaction ID'),
        color=alt.Color('proba', scale=alt.Scale(scheme='reds'), legend=None),
        tooltip=['orig_index', 'proba', 'amt', 'merchant']
    ).properties(
        title=f'Top {top_n} Highest Risk Transactions',
        height=max(400, top_n * 25)
    ).configure_axis(
        grid=False,
        labelColor='#94a3b8',
        titleColor='#f8fafc'
    ).configure_view(
        strokeWidth=0
    )
    
    st.altair_chart(chart, width="stretch")

def render_fraud_network(df, focused_node=None, threshold=0.8):
    """
    Renders an interactive network graph of Cards <-> Merchants using streamlit-agraph.
    """
    
    # Interactive Graph using streamlit-agraph
    try:
        from streamlit_agraph import agraph, Node, Edge, Config
    except ImportError:
        st.error("Please install streamlit-agraph: pip install streamlit-agraph")
        return

    nodes = []
    edges = []
    node_ids = set()

    # focused_node logic
    # To avoid overwhelming the graph, we focus on the passed dataframe subset
    # df here is already filtered (e.g. only high risk, or specific neighborhood)
    
    # We iterate through the dataframe to build edges
    # Limit to top 100 to prevent browser crash if subset is large
    graph_df = df.head(100)
    
    try:
        from webapp.ui_helpers import clean_merchant_name
    except ModuleNotFoundError:
        from ui_helpers import clean_merchant_name
    
    for idx, row in graph_df.iterrows():
        # Entities
        card = str(row['cc_num'])[-4:] # Masked card
        merch = str(row['merchant'])
        merch_clean = clean_merchant_name(merch)  # Clean for display
        risk = row['proba']
        
        card_id = f"{card}"
        merch_id = f"{merch}"  # Use original for ID matching
        
        # Add Card Node (Red Circle)
        if card_id not in node_ids:
            nodes.append(Node(
                id=card_id, 
                label=f"💳 {card}", 
                size=25, 
                color="#fb7185", # Red
                title=f"Card ending {card}"
            )) 
            node_ids.add(card_id)
        
        # Add Merchant Node (Green Square) - CLEANED NAME
        if merch_id not in node_ids:
            nodes.append(Node(
                id=merch_id, 
                label=f"🏪 {merch_clean[:18]}", # Truncated clean name
                size=30, 
                color="#34d399", # Green
                symbolType="square",
                title=f"{merch_clean}"  # Full clean name in tooltip
            )) 
            node_ids.add(merch_id)
        
        # Edge
        edges.append(Edge(
            source=card_id, 
            target=merch_id, 
            label=f"{risk:.2f}",
            color="#94a3b8"
        ))

    config = Config(
        width=1200, 
        height=600, 
        directed=False, 
        physics=True, 
        hierarchical=False,
        nodeHighlightBehavior=True,
        highlightColor="#F7A072",
        collapsible=False
    )

    # Render Graph
    return_value = agraph(nodes=nodes, edges=edges, config=config)
    
    # Handle Click Event
    if return_value:
        st.info(f"Selected Entity: **{return_value}**")
        
        # Find transactions involving this entity
        # We search in the FULL dataframe if possible, but here we only have 'df' passed.
        # Ideally we should pass the full results_df to this function if we want deep search,
        # but 'df' here might be just high_risk. 
        # Let's search within the passed 'df' for now.
        
        mask = (df['merchant'] == return_value) | (df['cc_num'].astype(str).str.endswith(return_value))
        connected_tx = df[mask]
        
        if not connected_tx.empty:
            st.markdown(f"### 🔗 Connection Log: {return_value}")
            
            # Selectable Table
            sel_net = st.dataframe(
                connected_tx[['orig_index', 'merchant', 'amt', 'proba']],
                use_container_width=True,
                hide_index=True,
                selection_mode="single-row",
                on_select="rerun",
                key=f"net_sel_{return_value}_{random.randint(0,1000)}" # ensure uniqueness
            )
            
            if sel_net and sel_net.selection.rows:
                idx = sel_net.selection.rows[0]
                # Show Detail Dialog
                show_transaction_details(connected_tx.iloc[idx])
        else:
            st.warning("No transactions found for this entity in the current view.")


def style_dataframe_rows(df, threshold):
    """
    Applies styling to dataframe rows based on risk score.
    Returns a Styler object.
    """
    def highlight_risk(row):
        try:
            p = float(row.get('proba', 0))
            if p >= threshold:
                return ['background-color: rgba(251, 113, 133, 0.15); color: #fecdd3'] * len(row)
        except:
            pass
        return [''] * len(row)

    return df.style.apply(highlight_risk, axis=1).format({'proba': '{:.4f}', 'amt': '${:.2f}'})


def render_descriptive_stats(df):
    """
    Renders 3 descriptive charts: Hour of Day, Location Map, and Amount Distribution.
    """
    if df.empty:
        st.info("No high-risk transactions detected to analyze.")
        return

    col1, col2, col3 = st.columns(3)
    
    with col1:
        st.markdown("**Peak Transaction Hours**")
        if 'trans_date_trans_time' in df.columns:
            # Parse datetime
            try:
                # Optimized for speed: assume format is consistent or let to_datetime handle it
                df['hour'] = pd.to_datetime(df['trans_date_trans_time']).dt.hour
                hour_counts = df['hour'].value_counts().sort_index().reset_index()
                hour_counts.columns = ['Hour', 'Count']
                
                chart = alt.Chart(hour_counts).mark_bar().encode(
                    x=alt.X('Hour:O', title='Hour of Day'),
                    y=alt.Y('Count:Q', title='Transactions'),
                    tooltip=['Hour', 'Count'],
                    color=alt.value('#818cf8')
                ).configure_axis(
                    grid=False,
                    labelColor='#94a3b8',
                    titleColor='#f8fafc'
                ).configure_view(strokeWidth=0).properties(height=200)
                
                st.altair_chart(chart, width="stretch")
            except Exception as e:
                st.warning(f"Could not parse dates: {e}")
        else:
            st.info("No time data available.")

    with col2:
        st.markdown("**Transaction Locations**")
        if 'lat' in df.columns and 'long' in df.columns:
            # Simple map
            map_data = df[['lat', 'long']].dropna()
            map_data = map_data.rename(columns={'long': 'lon'}) # Rename to match Streamlit expectation
            if not map_data.empty:
                # Sample if too large to prevent slow render
                if len(map_data) > 1000:
                    map_data = map_data.sample(1000)
                st.map(map_data, zoom=3, size=20, color='#38bdf8', height=200, use_container_width=True)
            else:
                st.warning("No valid coordinates found.")
        else:
            st.info("No location data available.")

    with col3:
        st.markdown("**Amount Distribution**")
        if 'amt' in df.columns:
            base = alt.Chart(df).encode(alt.X('amt', bin=alt.Bin(maxbins=20), title='Amount ($)'))
            chart = base.mark_bar().encode(
                y=alt.Y('count()', title='Count'),
                color=alt.value('#34d399'),
                tooltip=['count()']
            ).configure_axis(
                    grid=False,
                    labelColor='#94a3b8',
                    titleColor='#f8fafc'
            ).configure_view(strokeWidth=0).properties(height=200)
            
            st.altair_chart(chart, width="stretch")
        else:
            st.info("No amount data available.")

@st.dialog("🚨 Deep Risk Analysis", width="large")
def show_transaction_details(row):
    """
    Forensic Report style dialog for transaction details.
    """
    st.markdown("""
        <style>
        .dna-label { font-size: 0.8rem; color: #94a3b8; text-transform: uppercase; margin-bottom: 2px; }
        .dna-value { font-size: 1.1rem; color: #f8fafc; font-weight: 600; margin-bottom: 8px; font-family: 'Courier New', monospace; }
        .compact-header { 
            font-size: 1.25rem; 
            font-weight: 700; 
            color: #f8fafc; 
            margin: 0 0 8px 0; 
            padding-bottom: 4px; 
            border-bottom: 1px solid rgba(255, 255, 255, 0.1); 
            display: flex;
            align-items: center;
        }
        .compact-header span { margin-right: 8px; }
        </style>
    """, unsafe_allow_html=True)
    
    import time  # Import at start to avoid UnboundLocalError from later import
    
    col_left, col_right = st.columns([1, 1.5], gap="large")

    with col_left:
        st.markdown('<div class="compact-header"><span>🧬</span> Transaction DNA</div>', unsafe_allow_html=True)
        
        st.markdown('<p class="dna-label">Transaction ID</p>', unsafe_allow_html=True)
        st.markdown(f'<p class="dna-value">{row["orig_index"]}</p>', unsafe_allow_html=True)

        try:
            from webapp.ui_helpers import clean_merchant_name
        except ModuleNotFoundError:
            from ui_helpers import clean_merchant_name
        st.markdown('<p class="dna-label">Merchant Entity</p>', unsafe_allow_html=True)
        st.markdown(f'<p class="dna-value">{clean_merchant_name(row["merchant"])}</p>', unsafe_allow_html=True)
        
        st.markdown('<p class="dna-label">Amount</p>', unsafe_allow_html=True)
        st.markdown(f'<p class="dna-value" style="color:#ef4444;">${row["amt"]:,.2f}</p>', unsafe_allow_html=True)

        st.markdown('<p class="dna-label">Card Fingerprint</p>', unsafe_allow_html=True)
        st.markdown(f'<p class="dna-value">**** **** **** {str(row["cc_num"])[-4:]}</p>', unsafe_allow_html=True)

        st.markdown('<p class="dna-label">Timestamp</p>', unsafe_allow_html=True)
        st.markdown(f'<p class="dna-value">{row.get("trans_date_trans_time", "Unknown")}</p>', unsafe_allow_html=True)
        
        st.markdown("---")
        st.caption("Metadata verified by Graphite Ledger v2.1")

    with col_right:
        st.markdown('<div class="compact-header"><span>🤖</span> Explainability/Recommendation</div>', unsafe_allow_html=True)
        
        # report content without avatar icon
        with st.container():
            message_placeholder = st.empty()
            full_response = ""
            
            # Generate the sophisticated report
            analysis_text = generate_single_transaction_report(row)

            # Stream the response with a "typing_effect"
            for chunk in analysis_text.split(" "):
                full_response += chunk + " "
                time.sleep(0.01) # Ultra fast
                message_placeholder.markdown(full_response + "▌")
            message_placeholder.markdown(full_response)
        
        st.markdown("")
        st.markdown("")
        col_btn1, col_btn2, col_btn3 = st.columns(3)
        with col_btn1:
             st.button("🔒 Freeze Card", type="primary", use_container_width=True)
        with col_btn2:
             if st.button("📄 Generate SAR", use_container_width=True):
                 # Stage 9: Automated SAR Generation
                 # import time # REMOVED: Shadows global time module
                 report_id = f"SAR-{int(time.time())}-{row['orig_index']}"
                 sar_content = f"""
SUSPICIOUS ACTIVITY REPORT (SAR)
--------------------------------
Report ID: {report_id}
Date: {time.strftime("%Y-%m-%d %H:%M:%S")}
Status: Draft / Auto-Generated

SUBJECT INFORMATION
-------------------
Entity ID: {row['orig_index']}
Card Number: **** **** **** {str(row['cc_num'])[-4:]}
Merchant: {clean_merchant_name(row['merchant'])}
Transaction Amount: ${row['amt']:.2f}
Timestamp: {row.get('trans_date_trans_time', 'N/A')}

RISK ANALYSIS
-------------
Risk Score: {row['proba']:.4f}
Category: {row['category']}
Primary Indicators: High-velocity transaction pattern detected.

NARRATIVE
---------
This transaction was flagged by the Graphite-AI system due to anomalies consistent with 
established fraud patterns. The user is advised to review the attached network graph evidence.

ACTION TAKEN
------------
[ ] Account Frozen
[ ] Customer Contacted
[ ] Law Enforcement Notified

generated by Graphite Ledger v2.1
                 """

                 
                 # Save to SQLite Database (Stage 9 + Migration)
                 # We need to ensure actions_db is available here
                 try:
                     import webapp.actions_db as actions_db
                     actions_db.log_sar(report_id, row['orig_index'], sar_content)
                     st.toast(f"Report {report_id} securely archived in GraphDB.", icon="🗄️")
                 except ImportError:
                     # Fallback if module path issue
                     try:
                        import actions_db
                        actions_db.log_sar(report_id, row['orig_index'], sar_content)
                        st.toast(f"Report {report_id} securely archived in GraphDB.", icon="🗄️")
                     except Exception as e:
                        st.error(f"Database logging failed: {e}")

                 # also keep file backup for user download convenience if needed, or remove.
                 # User asked to "push storage to sqlite", implies replacement or primary.
                 # I'll keep file generation as a "downloadable feature" but the persistence is DB.
                 import os
                 if not os.path.exists("reports"): os.makedirs("reports")
                 with open(f"reports/{report_id}.txt", "w") as f:
                     f.write(sar_content)
                 # st.toast(f"SAR Generated: reports/{report_id}.txt", icon="📄")
        
        with col_btn3:
             if st.button("👮 Notify Authority", use_container_width=True, type="primary"):
                 # Create authority notification entry
                 import os
                 
                 # Create single-transaction dataframe for authority report
                 single_tx_df = pd.DataFrame([row])
                 
                 # Save to SQLite
                 try:
                     import webapp.actions_db as actions_db
                     report_id = actions_db.log_authority_report("Single-High", single_tx_df)
                     st.toast(f"✅ Authority notified! Report ID: {report_id}", icon="👮")
                 except ImportError:
                     try:
                         import actions_db
                         report_id = actions_db.log_authority_report("Single-High", single_tx_df)
                         st.toast(f"✅ Authority notified! Report ID: {report_id}", icon="👮")
                     except Exception as e:
                         st.error(f"Authority notification failed: {e}")
                 
                 # Also save CSV backup
                 report_dir = "reports"
                 if not os.path.exists(report_dir):
                     os.makedirs(report_dir)
                 
                 timestamp = time.strftime("%Y%m%d-%H%M%S")
                 filename = f"authority_alert_{row['orig_index']}_{timestamp}.csv"
                 filepath = os.path.join(report_dir, filename)
                 single_tx_df.to_csv(filepath, index=False)
                 
                 st.success(f"🚨 Transaction flagged and submitted to authorities.\n\n**Report saved:** `{filepath}`")

        # Stage 5: Adaptive Learning & Intelligence Feedback
        st.markdown("---")
        st.write("**🧠 Adaptive Intelligence Feedback**")
        c_feed1, c_feed2 = st.columns(2)
        with c_feed1:
            if st.button("✅ Confirm Fraud", use_container_width=True, type="primary"):
                with st.spinner("Updating Graph Embeddings & Retraining..."):
                    time.sleep(1.5) # Simulate work
                st.success("Model Updated (v2.1.4). Fraud pattern encoded.")
                st.toast("System Intelligence Increased", icon="📈")
        with c_feed2:
            if st.button("❌ False Positive", use_container_width=True):
                with st.spinner("Recalibrating Thresholds..."):
                    time.sleep(1.2)
                st.info("Weights Adjusted. Entity Whitelisted.")
                st.toast("Model Corrected", icon="🛡️")

    # 3. Feature Importance (SHAP) - Added as requested
    st.markdown("---")
    st.subheader("📊 Key Risk Drivers (AI Explainability)")
    
    shap_data = st.session_state.get('shap_data')
    if shap_data:
        # shap_data: {'idxs': [...], 'values': [[...]], 'columns': [...]}
        try:
             # Match current transaction ID with SHAP indices
             # Note: shap_data['idxs'] might be numpy array or list
             current_id = row['orig_index']
             
             # Find index in shap_data
             # We need to handle potential type mismatches (int vs str)
             shap_idxs = shap_data['idxs']
             target_pos = -1
             
             # efficient search
             if isinstance(shap_idxs, list):
                 if current_id in shap_idxs: target_pos = shap_idxs.index(current_id)
             else:
                 # assume numpy
                 matches = np.where(shap_idxs == current_id)[0]
                 if len(matches) > 0: target_pos = matches[0]
            
             if target_pos != -1:
                 try:
                     from webapp.ui_helpers import clean_feature_name
                 except ModuleNotFoundError:
                     from ui_helpers import clean_feature_name
                 shap_values = shap_data['values'][target_pos]
                 feature_names = shap_data['columns']
                 
                 # Create DF for chart with CLEANED feature names
                 shap_df = pd.DataFrame({
                     'Feature': [clean_feature_name(f) for f in feature_names],
                     'SHAP Value': shap_values,
                     'Abs Value': np.abs(shap_values)
                 }).sort_values('Abs Value', ascending=False).head(8) # Top 8 features
                 
                 # Render Chart
                 chart = alt.Chart(shap_df).mark_bar().encode(
                        x=alt.X('SHAP Value', title='Impact on Risk Score'),
                        y=alt.Y('Feature', sort='-x', title=None),
                        color=alt.condition(
                            alt.datum['SHAP Value'] > 0,
                            alt.value('#ef4444'),  # Red for risk increase
                            alt.value('#10b981')   # Green for risk decrease
                        ),
                        tooltip=['Feature', 'SHAP Value']
                    ).properties(
                        height=300
                    ).configure_axis(
                        grid=False,
                        labelColor='#94a3b8',
                        titleColor='#f8fafc',
                        labelFontSize=11
                    ).configure_view(strokeWidth=0)
                 
                 st.altair_chart(chart, use_container_width=True)
             else:
                 st.info("Detailed feature explanations not available for this specific transaction (not in top SHAP sample).")
        except Exception as e:
            st.warning(f"Could not load feature graph: {e}")
    else:
        st.info("SHAP explanations are not enabled or data is missing. Run the scan with 'Enable SHAP' checked.")


def render_interactive_risk_dashboard(df, top_n=50):
    """
    Renders the Executive Risk Dashboard with Risk Level Drill-Down.
    """
    # State Management for Drill-Down
    if 'dash_view' not in st.session_state:
        st.session_state.dash_view = 'summary' # summary | detail
    if 'selected_severity' not in st.session_state:
        st.session_state.selected_severity = None # High | Medium | Low | All

    # Calculate Data Subsets
    # df is the full dataset (or whatever is passed)
    # subset logic:
    high_risk = df[df['proba'] > 0.8]
    med_risk = df[(df['proba'] > 0.5) & (df['proba'] <= 0.8)]
    low_risk = df[df['proba'] <= 0.5]
    
    # Counts
    count_high = len(high_risk)
    count_med = len(med_risk)
    count_low = len(low_risk)
    count_all = len(df)
    
    # Header
    st.markdown("## 📋 Executive Risk Monitor")

    # VIEW 1: SUMMARY (Severity Buttons)
    if st.session_state.dash_view == 'summary':
        
        st.markdown("### 🚦 Risk Overview & Filtering")
        st.markdown("Select a risk level to view detailed transaction logs.")
        
        # 4 Big Buttons for Risk Levels
        # We use columns and standard buttons, styled to look like cards if possible, 
        # or just functional buttons. User asked for "BUTTON... HIGH, MEDIUM, LOW and ALL"
        
        b1, b2, b3, b4 = st.columns(4)
        
        with b1:
            # High Risk
            st.error(f"CRITICAL (High)\n# {count_high}")
            if st.button("🔴 View High Risk", use_container_width=True):
                st.session_state.selected_severity = 'High'
                st.session_state.dash_view = 'detail'
                st.rerun()
        
        with b2:
            # Medium Risk
            st.warning(f"ELEVATED (Medium)\n# {count_med}")
            if st.button("🟠 View Medium Risk", use_container_width=True):
                st.session_state.selected_severity = 'Medium'
                st.session_state.dash_view = 'detail'
                st.rerun()
                
        with b3:
            # Low Risk
            st.success(f"NORMAL (Low)\n# {count_low}")
            if st.button("🟢 View Low Risk", use_container_width=True):
                st.session_state.selected_severity = 'Low'
                st.session_state.dash_view = 'detail'
                st.rerun()

        with b4:
            # All
            st.info(f"TOTAL LOGS\n# {count_all}")
            if st.button("⚪ View All Logs", use_container_width=True):
                st.session_state.selected_severity = 'All'
                st.session_state.dash_view = 'detail'
                st.rerun()
        
        st.markdown("---")



    # VIEW 2: DRILL-DOWN (Detail Table)
    elif st.session_state.dash_view == 'detail':
        selected_sev = st.session_state.selected_severity
        
        # Navigation
        c_back, c_title = st.columns([1, 6])
        with c_back:
            if st.button("← Back", use_container_width=True):
                st.session_state.dash_view = 'summary'
                st.session_state.selected_severity = None
                st.rerun()
        
        # Filter Data
        if selected_sev == 'High':
            display_df = high_risk.copy()
            title_text = f"🔴 High Risk Transactions ({len(display_df)})"
        elif selected_sev == 'Medium':
            display_df = med_risk.copy()
            title_text = f"🟠 Medium Risk Transactions ({len(display_df)})"
        elif selected_sev == 'Low':
            display_df = low_risk.copy()
            title_text = f"🟢 Low Risk Transactions ({len(display_df)})"
        else:
            display_df = df.copy()
            title_text = f"⚪ All Transactions ({len(display_df)})"
        
        # Show empty state if no data
        if display_df.empty:
            st.markdown(f"### {title_text}")
            st.markdown("""
                <div class="empty-state">
                    <div class="empty-state-icon">✨</div>
                    <h3 style="color: var(--text-primary); margin-bottom: 0.5rem;">No Transactions Found</h3>
                    <p style="color: var(--text-secondary); margin-bottom: 1.5rem;">
                        There are currently no transactions in this risk category.
                    </p>
                </div>
            """, unsafe_allow_html=True)
            return

        # Header with Title and Report Button
        c_title_text, c_report = st.columns([3, 1])
        with c_title_text:
            st.markdown(f"### {title_text}")
        with c_report:
            if st.button(f"📥 Report {selected_sev} to Authority", type="primary", use_container_width=True):
                # Save to local reports folder
                import os
                import time
                report_dir = "reports"
                if not os.path.exists(report_dir):
                    os.makedirs(report_dir)
                
                timestamp = time.strftime("%Y%m%d-%H%M%S")
                filename = f"authority_report_{selected_sev}_{timestamp}.csv"
                filepath = os.path.join(report_dir, filename)
                
                display_df.to_csv(filepath, index=False)
                
                # Save to SQLite (Stage 9 + Migration)
                try:
                    import webapp.actions_db as actions_db
                    auth_id = actions_db.log_authority_report(str(selected_sev), display_df)
                    st.toast(f"Authority Report {auth_id} logged to GraphDB.", icon="🗄️")
                except ImportError:
                     try:
                        import actions_db
                        auth_id = actions_db.log_authority_report(str(selected_sev), display_df)
                        st.toast(f"Authority Report {auth_id} logged to GraphDB.", icon="🗄️")
                     except Exception as e:
                        st.error(f"Database logging failed: {e}")
                
                st.toast(f"Report submitted! Archived at: {filepath}", icon="👮")
                st.success(f"✅ Data for {len(display_df)} transactions has been securely logged to `{filepath}` and `data/graphdb.db` for authority review.")
            
        # Limit to top N for display if All/Low is huge?
        # User didn't specify, but for performance, maybe head? 
        # "then after clicking the Detail table Diplay" implies showing the table.
        # Let's cap at 100 for safety in "All" view if it's huge, or just show it.
        # Given it's a "Top 50" dashboard originally, we might want to sort by risk 
        # even within Low/Med categories.
        
        display_df = display_df.sort_values('proba', ascending=False).head(100) # Safety cap
        
        # Render Table if data exists
        if not display_df.empty:
            # Add Risk Level Column
            # Add Risk Level Column and Automated Action
            def get_risk_analysis(score):
                if score > 0.95: return "🔴 High", "🚨 Suspend Network Cluster"
                if score > 0.8: return "🔴 High", "❄️ Freeze Account"
                if score > 0.5: return "🟠 Medium", "🔐 Step-up Auth"
                return "🟢 Low", "👀 Monitor"
            
            # Apply to create two new columns
            display_df[['Risk Level', 'Action']] = display_df['proba'].apply(
                lambda x: pd.Series(get_risk_analysis(x))
            )
            
            if 'orig_index' not in display_df.columns:
                display_df['orig_index'] = display_df.index
            
            # Clean merchant and category names for display
            try:
                from webapp.ui_helpers import clean_merchant_name
            except ModuleNotFoundError:
                from ui_helpers import clean_merchant_name
            display_df = display_df.copy()
            display_df['merchant'] = display_df['merchant'].apply(clean_merchant_name)
            
            # Clean category names (remove underscores, title case)
            display_df['category'] = display_df['category'].apply(
                lambda x: str(x).replace('_', ' ').title() if pd.notna(x) else 'Unknown'
            )
            
            # Columns
            cols_to_show = ['orig_index', 'Risk Level', 'Action', 'proba', 'amt', 'merchant', 'is_fraud', 'category']
            final_df = display_df[[c for c in cols_to_show if c in display_df.columns]].copy()
            
            
            # Styling - removed red background per user request
            def highlight_danger(row):
                return [''] * len(row)

            styler = final_df.style.apply(highlight_danger, axis=1)

            selection = st.dataframe(
                styler,
                use_container_width=True,
                hide_index=True,
                on_select="rerun",
                selection_mode="single-row",
                column_config={
                    "orig_index": st.column_config.TextColumn("ID"),
                    "Risk Level": st.column_config.TextColumn("Status"),
                    "Action": st.column_config.TextColumn("Recommended Action"),
                    "proba": st.column_config.ProgressColumn("Score", format="%.2f", min_value=0, max_value=1),
                    "amt": st.column_config.NumberColumn("Amount", format="$%.2f"),
                    "merchant": st.column_config.TextColumn("Merchant"),
                    "category": st.column_config.TextColumn("Category")
                }
            )
            
            if selection and selection.selection.rows:
                selected_index = selection.selection.rows[0]
                full_row = display_df.iloc[selected_index]
                show_transaction_details(full_row)
            
            # --- Network Graph Integration ---
            # "visualize network graph should display only when a particular category show"
            # We show it for the filtered subset in the detail view.
            st.markdown("---")
            st.subheader("🕸️ Network Forensics (Filtered Subset)")
            st.caption(f"Visualizing connections for the displayed {len(display_df)} transactions.")
            render_fraud_network(display_df, threshold=0.5)
        else:
            st.info("No records found for this risk level.")


import datetime

def get_report_files(reports_dir='reports'):
    """
    Scans the reports directory, groups files, and extracts metadata (dates).
    """
    if not os.path.exists(reports_dir):
        return {}
    
    files = os.listdir(reports_dir)
    report_data = []
    
    for f in files:
        path = os.path.join(reports_dir, f)
        if not os.path.isfile(path): continue
        
        # Extract date
        dt = None
        category = "Other"
        
        # Pattern 1: authority_report_Low_20260214-233459.csv
        date_match = re.search(r'(\d{8})-(\d{6})', f)
        if date_match:
            try:
                dt = datetime.datetime.strptime(date_match.group(1), '%Y%m%d').date()
            except: pass
            
        # Pattern 2: SAR-1771077750-784.txt
        if not dt:
            sar_match = re.search(r'SAR-(\d+)', f)
            if sar_match:
                try:
                    dt = datetime.datetime.fromtimestamp(int(sar_match.group(1))).date()
                except: pass
        
        # Fallback to file mtime if no date in name
        if not dt:
            dt = datetime.datetime.fromtimestamp(os.path.getmtime(path)).date()

        # Grouping
        if f.startswith('SAR-'): category = "SAR Reports"
        elif f.startswith('authority_alert_') or f.startswith('authority_report_'): 
            category = "Authority Correspondence"
        
        report_data.append({
            'filename': f,
            'category': category,
            'date': dt,
            'size': os.path.getsize(path)
        })
        
    return pd.DataFrame(report_data)

def render_report_explorer(reports_dir='reports'):
    """
    Renders the simplified report explorer UI.
    """
    st.markdown("## 📂 Forensic Report Explorer")
    
    df_reports = get_report_files(reports_dir)
    if df_reports.empty:
        st.info("No reports found in the system.")
        return

    # Top Controls for Filtering
    with st.container(border=True):
        col1, col2 = st.columns([1, 1])
        with col1:
            min_date = df_reports['date'].min()
            max_date = df_reports['date'].max()
            date_range = st.date_input("Date Range", value=(min_date, max_date), min_value=min_date, max_value=max_date)
        with col2:
            search = st.text_input("Search Reports", placeholder="e.g. SAR-1771 or Merchant...")

    # Apply Filters
    df_filtered = df_reports.copy()
    if len(date_range) == 2:
        start_date, end_date = date_range
        mask = (df_filtered['date'] >= start_date) & (df_filtered['date'] <= end_date)
        df_filtered = df_filtered[mask]
        
    if search:
        df_filtered = df_filtered[df_filtered['filename'].str.contains(search, case=False)]

    # Batch Analysis View (Default/Unified)
    render_batch_analysis(df_filtered, reports_dir)

def render_batch_analysis(df_reports, reports_dir):
    st.markdown("### 📊 Aggregate Reports Analysis")
    
    # Metrics
    m1, m2, m3 = st.columns(3)
    m1.metric("Total Artifacts", len(df_reports))
    m2.metric("SARs Filed", len(df_reports[df_reports['category'] == 'SAR Reports']))
    m3.metric("Authority Syncs", len(df_reports[df_reports['category'] == 'Authority Correspondence']))

    # Volume Chart
    st.markdown("#### Forensic Volume Over Time")
    df_vol = df_reports.groupby('date').size().reset_index(name='count')
    chart = alt.Chart(df_vol).mark_line(point=True, color='#38bdf8').encode(
        x='date:T',
        y='count:Q',
        tooltip=['date', 'count']
    ).properties(height=200)
    st.altair_chart(chart, use_container_width=True)

    # Category Distribution Pie Chart
    st.markdown("#### Distribution by Report Type")
    df_cat = df_reports['category'].value_counts().reset_index()
    # Define a custom color scheme for the merged categories
    category_colors = alt.Scale(
        domain=['SAR Reports', 'Authority Correspondence'],
        range=['#ef4444', '#38bdf8'] # Red for SAR, Blue for Authority
    )
    
    pie = alt.Chart(df_cat).mark_arc(innerRadius=60).encode(
        theta=alt.Theta(field="count", type="quantitative"),
        color=alt.Color(field="category", type="nominal", scale=category_colors, legend=alt.Legend(title="Report Category")),
        tooltip=['category', 'count']
    ).properties(height=300)
    st.altair_chart(pie, use_container_width=True)

    # Detailed List Table with Selection
    st.markdown("#### Forensic Artifact Explorer")
    st.caption("Click a row to preview the report content below.")
    
    selection = st.dataframe(
        df_reports[['filename', 'category', 'date', 'size']], 
        use_container_width=True, 
        hide_index=True,
        on_select="rerun",
        selection_mode="single-row"
    )

    if selection and selection.selection.rows:
        idx = selection.selection.rows[0]
        selected_file = df_reports.iloc[idx]['filename']
        st.markdown("---")
        render_file_preview(reports_dir, selected_file)

def render_file_preview(reports_dir, filename):
    file_path = os.path.join(reports_dir, filename)
    file_ext = os.path.splitext(filename)[1].lower()
    
    st.markdown(f"### 📄 Preview: {filename}")
    try:
        if file_ext == '.txt':
            with open(file_path, 'r') as f:
                content = f.read()
            st.markdown(f"```text\n{content}\n```")
            st.download_button("Download TXT", content, file_name=filename)
        elif file_ext == '.csv':
            df = pd.read_csv(file_path)
            st.dataframe(df, use_container_width=True)
            csv_bytes = df.to_csv(index=False).encode('utf-8')
            st.download_button("Download CSV", csv_bytes, file_name=filename, mime='text/csv')
    except Exception as e:
        st.error(f"Error previewing: {e}")
